### ISSUE TITLE
Activate CCTL failed

### ISSUE THREAD

**Issue by Jiuhong-casperlabs** [casper-network/cctl#5]
After the CCTL Setup I tried Activate CCTL but failed with the message:
```
jh@DESKTOP-RMF966H:~/caspereco/cctl (main)
$ . ./home/jh/caspereco/cctl/activate
bash: ./home/jh/caspereco/cctl/activate: No such file or directory
```

```
jh@DESKTOP-RMF966H:~/caspereco/cctl (main)
$ ls
LICENSE  README.md  activate  cmds  docker  docs  installer  resources  scripts  utils
```
Can you take a look what is wrong?

**Comment by asladeofgreen** [comment]
@Jiuhong-casperlabs 

1. Could you please clarify which shell and OS you are using ?  
2. If you are using bash shell then I cannot see how the file cannot be found.

**Comment by Jiuhong-casperlabs** [comment]
@asladeofgreen 
The OS is Ubuntu 22.04.3 LTS on WSL2.
The shell is `/bin/bash`.

Do you need more info? Or what should I try further?

**Comment by asladeofgreen** [comment]
When you have spare time could you please try again but via manual install rather than trying the installer script which is untested ATM.

**Comment by Jiuhong-casperlabs** [comment]
Yes, manually installing works fine. 
Thank you. I will close it.
